export const buyerPage = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AI-Assisted B2B Order Approval · Buyer demo</title><style>
:root{font-family:Inter,ui-sans-serif,system-ui,sans-serif;color:#152b35;background:#f2f5f3}*{box-sizing:border-box}body{margin:0}header{background:#102b2c;color:#f6faf5;padding:28px max(24px,calc((100vw - 1120px)/2));display:flex;justify-content:space-between;align-items:center;gap:20px}header strong{font-size:18px;letter-spacing:-.5px}header a{color:#d5f597;font-size:14px}main{max-width:1120px;margin:48px auto;padding:0 24px}h1{font-size:clamp(30px,5vw,48px);line-height:1.1;letter-spacing:-1.8px;margin:12px 0 18px}h2{font-size:21px;letter-spacing:-.5px;margin:0 0 18px}p{line-height:1.6}.eyebrow{font-size:11px;font-weight:750;letter-spacing:2px;text-transform:uppercase;color:#55736c}.intro{max-width:740px;color:#526960}.layout{display:grid;grid-template-columns:1.1fr 1fr;gap:24px;margin:32px 0}.card{background:#fff;border:1px solid #d9e3dc;border-radius:16px;padding:28px;box-shadow:0 4px 18px #102b2c04}.full{grid-column:1/-1}label{display:block;font-size:13px;font-weight:650;margin:16px 0 7px}input,select{width:100%;padding:12px;border:1px solid #b9cbc0;border-radius:8px;font:inherit;color:#152b35;background:white}button{padding:12px 18px;border-radius:8px;border:1px solid #102b2c;background:#102b2c;color:white;cursor:pointer;font-weight:650;font-size:14px}button.secondary{background:white;color:#102b2c;border-color:#bacdc0}button:disabled{opacity:.45;cursor:wait}button:focus-visible,a:focus-visible{outline:3px solid #80a638;outline-offset:3px}.buttons{display:flex;gap:10px;margin-top:20px;flex-wrap:wrap}.muted{color:#60756e;font-size:13px}.note{border-left:3px solid #a9c974;padding:10px 16px;background:#f1f7e7;font-size:13px;line-height:1.6}.tag{background:#e5eedf;border-radius:100px;padding:6px 12px;font-size:12px;font-weight:650}.tag.pending{background:#fff0c8;color:#775700}.tag.approved{background:#dff4df;color:#176536}.tag.rejected{background:#fde7e3;color:#9a3323}.request{border-top:1px solid #e2e9e3;padding:20px 0}.request-top{display:flex;justify-content:space-between;gap:16px;align-items:center}.mono{font-family:ui-monospace,monospace;font-size:11px;overflow-wrap:anywhere;color:#647b72}.amount{font-size:30px;letter-spacing:-1px;font-weight:650;margin:12px 0}#message{padding:15px 20px;margin:20px 0;border-radius:10px;background:#e5eedf;white-space:pre-wrap}#message.error{background:#fde7e3;color:#8c2919}.hidden{display:none!important}.row{display:flex;align-items:center;justify-content:space-between;gap:12px}footer{font-size:12px;color:#71867b;padding:20px 0 40px}code{font-size:12px}@media(max-width:700px){.layout{grid-template-columns:1fr}main{margin-top:28px}.card{padding:20px}header{padding:22px 24px}}
</style></head><body>
<header><strong>Rigby portfolio / B2B</strong><a href="/app/approvals" target="_blank" rel="noopener">Open Medusa Admin ↗</a></header>
<main><span class="eyebrow">Medusa v2 · Agent orchestration</span><h1>Three agents.<br>One human decision.</h1><p class="intro">Submit a Medusa cart. Policy, Risk and Recommendation agents analyze it in sequence. Your account manager reviews their evidence and makes the final decision.</p>
<div class="note"><strong>__MODE_LABEL__</strong><br>Approval only. No order is placed, no payment is collected, and the Medusa cart remains open. A decision applies to the saved snapshot, even if the cart later changes.</div>
<div id="message" class="hidden" role="status" aria-live="polite"></div>
<div class="layout"><section class="card" id="login-card"><span class="eyebrow">01 / Buyer account</span><h2 style="margin-top:12px">Sign in to your company</h2><form id="login"><label for="email">Email</label><input id="email" type="email" autocomplete="username" value="buyer@acme.demo" required><label for="password">Password</label><input id="password" type="password" autocomplete="current-password" value="RigbyDemo2026!" required><div class="buttons"><button type="submit">Sign in</button></div></form><p class="muted">Local demo credentials are prefilled. Run <code>npm run seed</code> first.</p></section>
<section class="card hidden" id="company-card"><span class="eyebrow">01 / Your company</span><h2 id="company" style="margin-top:12px"></h2><p class="muted">Approval required above</p><div class="amount" id="limit"></div><p class="muted" id="identity"></p><button class="secondary" id="logout">Sign out</button></section>
<section class="card"><span class="eyebrow">02 / Purchase request</span><h2 style="margin-top:12px">Choose a demo scenario</h2><p class="muted">Office supply kits · PLN 450.00 each<br>Server-owned catalogue. The outage is injected only in DEMO mode; LIVE uses real API calls.</p><label for="basket">Scenario</label><select id="basket"><option value="clean">1. Routine purchase · PLN 1,350 · suggested approval</option><option value="manual">2. Unplanned expansion · PLN 9,000 · manual review</option><option value="failure">3. Risk Agent outage · PLN 1,350 · simulated failure</option><option value="injection">4. Product prompt injection · PLN 1,350 · guardrails</option></select><p class="muted" id="description"></p><div class="buttons"><button id="create" disabled>Create cart</button><button id="submit" class="secondary" disabled>Submit for approval</button></div><p class="mono" id="cart">Sign in to create a cart.</p></section>
<section class="card full"><div class="row"><div><span class="eyebrow">03 / Company activity</span><h2 style="margin-top:12px">Requests & decisions</h2></div><button class="secondary" id="refresh" disabled>Refresh status</button></div><p class="muted">Includes requests from members of your company. Switch to Admin to review, then refresh here.</p><div id="requests"><p class="muted">Sign in to see your company's requests.</p></div></section></div>
<footer>AI-Assisted B2B Order Approval · Medusa v2 + PostgreSQL · Built for a Rigby recruitment demo</footer></main>
<script>
let token='', cartId='', busy=false;
const $=id=>document.getElementById(id);
const money=(n,c='pln')=>new Intl.NumberFormat('en-GB',{style:'currency',currency:c}).format(n/100);
function message(text,error=false){$('message').textContent=text;$('message').className=error?'error':''}
function controls(){document.querySelectorAll('button').forEach(b=>b.disabled=busy);$('create').disabled=busy||!token;$('submit').disabled=busy||!token||!cartId;$('refresh').disabled=busy||!token}
async function call(path,options={}){const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{}),...options.headers}});const body=await r.json();if(!r.ok)throw Error(body.message||'Request failed ('+r.status+')');return body}
async function run(fn){if(busy)return;busy=true;controls();try{await fn()}catch(e){message(e.message,true)}finally{busy=false;controls()}}
function node(tag,text,cls){const n=document.createElement(tag);n.textContent=text;if(cls)n.className=cls;return n}
async function refresh(){const data=await call('/b2b/requests');$('requests').replaceChildren();if(!data.approval_requests.length)$('requests').append(node('p','No requests yet. Create a cart and submit it for approval.','muted'));for(const r of data.approval_requests){const card=node('article','','request');const top=node('div','','request-top');top.append(node('strong',money(r.amount_minor,r.currency_code)),node('span',r.status,'tag '+r.status));card.append(top,node('p','Agent analysis: '+(r.current_run_id?r.analysis_status:'legacy')+(r.recommendation?' · Recommendation: '+r.recommendation.replaceAll('_',' '):''),'muted'),node('p',r.id,'mono'),node('p','Limit at submission: '+money(r.limit_minor,r.currency_code)+' · '+new Date(r.created_at).toLocaleString("en-GB"),'muted'));if(r.reason){card.append(node('p',r.reason),node('p','Decided: '+new Date(r.decided_at).toLocaleString("en-GB"),'muted'))}else{card.append(node('p','Waiting for your account manager.','muted'))}card.append(node('p','Cart: '+r.cart_id+' · Not checked out','mono'));$('requests').append(card)}if(data.count>100)$('requests').append(node('p','Showing the latest 100 requests.','muted'))}
$('login').onsubmit=e=>{e.preventDefault();run(async()=>{const data=await call('/auth/customer/emailpass',{method:'POST',body:JSON.stringify({email:$('email').value,password:$('password').value})});token=data.token;try{const me=await call('/b2b/me');$('company').textContent=me.company.name;$('limit').textContent=money(me.company.approval_limit_minor,me.company.currency_code);$('identity').textContent=$('email').value+' · '+(me.member.can_submit?'Can submit requests':'Read-only member');await refresh();$('login-card').classList.add('hidden');$('company-card').classList.remove('hidden');$('cart').textContent='Ready. Create a cart to begin.';message('Signed in. Your company scope is verified by the server.')}catch(e){token='';throw e}})};
$('logout').onclick=()=>{token='';cartId='';$('company-card').classList.add('hidden');$('login-card').classList.remove('hidden');$('requests').replaceChildren(node('p','Sign in to see your company requests.','muted'));$('cart').textContent='Sign in to create a cart.';controls();message('Signed out.')};
$('create').onclick=()=>run(async()=>{const data=await call('/b2b/carts',{method:'POST',body:JSON.stringify({basket:$('basket').value})});cartId=data.cart.id;$('cart').textContent='Open cart: '+cartId;$('description').textContent='Product description (untrusted): '+(data.cart.items?.[0]?.product_description||'');message('Cart created. Submit it to request approval. No order has been placed.')});
$('submit').onclick=()=>run(async()=>{const data=await call('/b2b/requests',{method:'POST',body:JSON.stringify({cart_id:cartId})});cartId='';$('cart').textContent='Snapshot submitted: '+data.approval_request.id;await refresh();message('Request submitted. Follow the agent timeline and human decision in Medusa Admin.')});
$('refresh').onclick=()=>run(async()=>{await refresh();message('Statuses refreshed from the server.')});
setInterval(()=>{if(token&&!busy)refresh().catch(()=>{});},2500);
</script></body></html>`;
